# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction.

What are the prerequisites, for both knowledge and e.g. software setup?

-   R, RStudio, and some required R packages
-   knowledge of what a hurricane is
-   General knowledge on how ggplot works
-   It is preferable that they know how shape data works hopefully I can get it figured out and help someone else figure it out to

What are the basic requirements for any data that the method is used on? - Are missing values allowed? - Should the data be confined within a certain range? - Does the data have to be approximately normally distributed?

-   For my method, I'd like to limit my data to that of Hurricane Katrina (2005), just for simplicity. There are many hurricane databases with multiple hurricanes but I don't know how that can help me with my task.

What are the basic components of the task? - Outline these in a bit more detail

-   Get Hurricane Katrina data that includes
    -   Longitude and Latitude data for eye path for sure
    -   Wind speed
    -   Damage
        -   This could be categorical ie Catastrophic, High, Low

What decisions does the user need to be prepared to make on the fly?

-   I want to supply the download for the csv file(s) so the user does not have to go hunt for some or I will list the websites from where I got them

What questions should the user ask of the "first draft" of the product? What adjustments may need to be made?

## Additional Guidance

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic).

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. This document should remain as an appendix to your main report.
